### PR TITLE
Fix SASS compilation errors

### PR DESCRIPTION
**Pull request by cedroux**
Files were called in wrong order causing following errors when compiling SASS:
```
$ ./scss.sh
>>> Sass is watching for changes. Press Ctrl-C to stop.
      error scss/agency.scss (Line 10: Undefined variable: "$secondary-dark".)
      error scss/bootstrap.min.scss (Line 7: Undefined variable: "$secondary".)
      write css-compiled/global.css
      write css-compiled/global.css.map

```

### CODE REVIEW

**Comment by ch3ckmat3** [comment]
any fix for this error?

**Comment by cedroux** [comment]
Yes, take a look at my commit (4c312ca)

**Comment by ch3ckmat3** [comment]
thanks, but this has not been merged, how can I apply this patch directly to my local clone?

**Comment by cedroux** [comment]
Just rename the following files:
`scss/agency.scss` to `scss/_agency.scss`
`scss/bootstrap.min.scss` to `scss/_bootstrap.min.scss`

Explanation here: http://sass-lang.com/guide#topic-4

**Comment by ch3ckmat3** [comment]
got it! thanks 👍

**Comment by flaviocopes** [comment]
I didn't get the error myself when compiling, I guess it's a configuration issue, but this fixes the unused css compilation of the agency and bootstrap scss files.

**Pull request merged**
